# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindows(object):
    def setupUi(self, Mainwindows):
        Mainwindows.setObjectName("Mainwindows")
        Mainwindows.resize(688, 514)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        Mainwindows.setFont(font)
        self.swExecute = QtWidgets.QPushButton(Mainwindows)
        self.swExecute.setGeometry(QtCore.QRect(60, 100, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.swExecute.setFont(font)
        self.swExecute.setObjectName("swExecute")
        self.label = QtWidgets.QLabel(Mainwindows)
        self.label.setGeometry(QtCore.QRect(230, 20, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.swEnableConveyor = QtWidgets.QPushButton(Mainwindows)
        self.swEnableConveyor.setGeometry(QtCore.QRect(60, 190, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.swEnableConveyor.setFont(font)
        self.swEnableConveyor.setObjectName("swEnableConveyor")
        self.swEnableConveyor.setStyleSheet("background-color : grey")
        self.swEnableConveyor.setCheckable(True)
        self.lcdNumber = QtWidgets.QLCDNumber(Mainwindows)
        self.lcdNumber.setGeometry(QtCore.QRect(60, 300, 141, 81))
        self.lcdNumber.setObjectName("lcdNumber")
        self.plotWidget = QtWidgets.QWidget(Mainwindows)
        self.plotWidget.setGeometry(QtCore.QRect(260, 100, 361, 301))
        self.plotWidget.setObjectName("plotWidget")
        self.label_2 = QtWidgets.QLabel(Mainwindows)
        self.label_2.setGeometry(QtCore.QRect(90, 380, 101, 41))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Mainwindows)
        QtCore.QMetaObject.connectSlotsByName(Mainwindows)

    def retranslateUi(self, Mainwindows):
        _translate = QtCore.QCoreApplication.translate
        Mainwindows.setWindowTitle(_translate("Mainwindows", "DeltaXrobot"))
        self.swExecute.setText(_translate("Mainwindows", "Execute"))
        self.label.setText(_translate("Mainwindows", "DeltaXrobotics"))
        self.swEnableConveyor.setText(_translate("Mainwindows", "Start Conv"))
        self.label_2.setText(_translate("Mainwindows", "complete"))
